//let root = null;
let width = 1700;
let  heigth = 600;
let time = 1000;
let count = 0;
let radius = 25;
const newAddedNodeBeginRootOfHeap = 1;
const newAddedNodeBeginTheRigthSonOfNode = 2;
let  mode;
let svg;