let width = /*1700*/ 1800;
let  heigth = 600;
let time = 500;
let count = 0;
let radius = 24;
const newAddedNodeBeginRootOfHeap = 1;
const newAddedNodeBeginTheRigthSonOfNode = 2;
let  mode;
const colorOfNode = '#e7adad';
const colorOfPass = '#960000';
const colorOfText = 'black';
let svg;
const leftLocationForSplit = 'left';
const rightLocationForSplit = 'right';
